---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.sh: 'internal/data/database/config'
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-database-config.sh: |
          {{ with secret "internal/data/database/config" -}}
            export username="{{ .Data.data.username }}"
            export password="{{ .Data.data.password }}"
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: web
          image: alpine:latest
          args:
            ['sh', '-c', 'source /vault/secrets/database-config.sh ; echo "username=$username password=$password" ; sleep 3600']
          ports:
            - containerPort: 9090